#!/bin/bash
pygmentsDir=site-packages/pygments/lexers
if [[ $(uname) = "Darwin" ]]; then
    sudo cp j.py /Library/Python/2.7/"$pygmentsDir"/
else
    sudo cp j.py /usr/lib/python2.7/"$pygmentsDir"/
fi
pygmentize -f html -O full -o output/test.html test.ijs
